Feat/realtime chat
transcendence42/ft_transcendence pull request #120
Opened 2021-07-21 07:10 UTC by yhshin0

> What was wrong/why is this fix needed? (quick summary only)

채팅 구현
- subscription(chatLogAdded) 구현
- 채팅 기능 구현
- 채팅방 입장 구현
- 비공개 채팅방 비밀번호 확인 구현

> Issue number (if there is an associated issue)

> Anything else that could help us review it

# GraphQL module subscription 적용
원래 apollo-server를 설정할 때 subsciption에 대한 설정을 적용하여 apollo-server instance를 생성하고 해당 역할을 할 수 있도록 합니다.
그러나 nestjs에는 @nestjs/graphql 이 제공하는 GraphQLModule이 apollo-server를 감싸는 wrapper이므로([https://docs.nestjs.com/graphql/quick-start](https://docs.nestjs.com/graphql/quick-start)), subscription 서버 설정을 GraphQLModule 안에 해줘야 합니다.

설정은 다음과 같이 적용합니다.

src/app.module.ts

```jsx
@Module({
  imports: [
    GraphQLModule.forRoot({
      autoSchemaFile: 'schema.gql',
      **installSubscriptionHandlers: true,
      subscriptions: {
        path: '/subscriptions',
        keepAlive: 5000,
      },**
    }),
    ...
```

- installSubscriptionHandlers는 subscription을 가능하게 하는 옵션입니다.
- subscriptions에는 subscription과 관련된 설정을 적용할 수 있습니다.
    - path: 서버의 subscription 엔드포인트의 경로입니다. 필수값이며, 웹소켓 프로토콜을 사용하므로 'ws://localhost:5500/<path>' 와 같은 형태로 접근이 가능합니다.
    - keepAlive: 열려 있는 클라이언트 연결에 Keep-Alive 메시지를 보내는 빈도(밀리초)입니다. 이 값이 제공되지 않으면 keep-alive 메시지를 보내지 않습니다.

> [https://www.apollographql.com/docs/apollo-server/v2/api/apollo-server/#subscription-configuration-fields](https://www.apollographql.com/docs/apollo-server/v2/api/apollo-server/#subscription-configuration-fields)

## Apollo-client 설정

subscription은 http로는 연결을 지속적으로 유지하기 어려우므로, 웹소켓 프로토콜을 사용합니다.
그리고 이를 위한 라이브러리인 `subscriptions-transport-ws` 를 설치합니다.

```jsx
yarn add subscriptions-transport-ws
```

apollo client를 초기화하는 곳에서 WebSocketLink를 초기화합니다.
이때 uri 주소는 서버의 subscription이 제공하는 uri와 일치해야 합니다.

```jsx
import { WebSocketLink } from '@apollo/client/link/ws';

const wsLink = new WebSocketLink({
  uri: 'ws://localhost:5500/subscriptions',
  options: {
    reconnect: true
  }
});
```

그런 다음 query와 mutation이 HTTP를, subscription이 WebSocket 프로토콜을 사용할 수 있도록 분리해줍니다.
WebSocketLink가 모든 operation을 처리할 수 있지만, query와 mutation은 상태를 저장하거나, 오래 지속되는 연결이 필요없기 때문에 HTTP가 더 적합합니다.
이를 위해 @apollo/client 라이브러리는 split 이라는 함수를 제공합니다. split은 체크 결과에 따라 두 개의 다른 링크 중 하나를 사용할 수 있도록 해줍니다.

```jsx
import { split, HttpLink } from '@apollo/client';
import { getMainDefinition } from '@apollo/client/utilities';
import { WebSocketLink } from '@apollo/client/link/ws';

const httpLink = new HttpLink({
  uri: 'http://localhost:5500/graphql'
});

const wsLink = new WebSocketLink({
  uri: 'ws://localhost:5500/subscriptions',
  options: {
    reconnect: true
  }
});

// The split function takes three parameters:
//
// * A function that's called for each operation to execute
// * The Link to use for an operation if the function returns a "truthy" value
// * The Link to use for an operation if the function returns a "falsy" value
const splitLink = split(
  ({ query }) => {
    const definition = getMainDefinition(query);
    return (
      definition.kind === 'OperationDefinition' &&
      definition.operation === 'subscription'
    );
  },
  wsLink,
  httpLink,
);
```

이후 link 옵션으로 Apollo Client에 연결합니다.
link 옵션을 사용하면 uri 옵션보다 우선시됩니다.

```jsx
import { ApolloClient, InMemoryCache } from '@apollo/client';

// ...code from the above example goes here...

const client = new ApolloClient({

  link: splitLink,
  cache: new InMemoryCache()
});
```

### Authenticate over WebSocket (optional)

subscription 결과를 받기 위해 인증(authenticate)이 필요할 수 있습니다.
이를 위해 WebSocketLink의 connectionParams 옵션을 사용하면 됩니다.

```jsx
import { WebSocketLink } from '@apollo/client/link/ws';

const wsLink = new WebSocketLink({
  uri: 'ws://localhost:5500/subscriptions',
  options: {
    reconnect: true,

    connectionParams: {
      authToken: user.authToken,
    },
  },
});
```

WebSocketLink는 connectionParams 객체를 연결할 때마다 서버에 전달합니다.
서버가 WebSocket 연결을 listen 할 SubscriptionsServer 객체를 갖고 있다면, connectionParams 객체를 받고 authentication을 수행할 수 있습니다.

## subscription 실행하기

리액트에서 subscription을 실행하기 위해 useSubscription 훅을 사용할 수 있습니다.
useQuery 처럼 useSubscription은 loading, error, data 속성을 가진 객체를 반환합니다.

다음 예제는 subscription을 사용하여 가장 최근 댓글을 렌더링하는 코드입니다.
GraphQL 서버가 새로운 댓글을 클라이언트에 push 할 때마다, 새 댓글과 함께 리렌더링됩니다.

```jsx
const COMMENTS_SUBSCRIPTION = gql`
  subscription OnCommentAdded($postID: ID!) {
    commentAdded(postID: $postID) {
      id
      content
    }
  }
`;

function LatestComment({ postID }) {
  const { data, loading } = useSubscription(
    COMMENTS_SUBSCRIPTION,
    { variables: { postID } }
  );
  return <h4>New comment: {!loading && data.commentAdded.content}</h4>;
}
```

## subscription으로 들어오는 데이터를 사용하여 query 업데이트하기

쿼리가 Apollo Client에 결과를 리턴할 때마다, 해당 결과는 subscribeToMore 함수에 포함됩니다.
이를 사용하여 기존의 데이터를 업데이트 할 수 있습니다.

먼저 다음 쿼리를 사용하여 데이터를 가져옵니다.

```jsx
const COMMENTS_QUERY = gql`
  query CommentsForPost($postID: ID!) {
    post(postID: $postID) {
      comments {
        id
        content
      }
    }
  }
`;

function CommentsPageWithData({ params }) {
  const result = useQuery(
    COMMENTS_QUERY,
    { variables: { postID: params.postID } }
  );
  return <CommentsPage {...result} />;
}
```

그리고 subscription 쿼리를 작성합니다.

```jsx
const COMMENTS_SUBSCRIPTION = gql`
  subscription OnCommentAdded($postID: ID!) {
    commentAdded(postID: $postID) {
      id
      content
    }
  }
`;
```

이후 UseQuery에서 subscribeToMore 함수를 받아와서 CommentsPage property로 넘겨줍니다.
subscribeToMore는 컴포넌트가 마운트 된 후에 호출되어 쿼리를 갱신하는 함수입니다.

```jsx
function CommentsPageWithData({ params }) {
  const { subscribeToMore, ...result } = useQuery(
    COMMENTS_QUERY,
    { variables: { postID: params.postID } }
  );

  return (
    <CommentsPage
      {...result}
      subscribeToNewComments={() =>
        subscribeToMore({
          document: COMMENTS_SUBSCRIPTION,
          variables: { postID: params.postID },
          updateQuery: (prev, { subscriptionData }) => {
            if (!subscriptionData.data) return prev;
            const newFeedItem = subscriptionData.data.commentAdded;
            return Object.assign({}, prev, {
              post: {
                comments: [newFeedItem, ...prev.post.comments]
              }
            });
          }
        })
      }
    />
  );
}
```

subscribeToMore의 각 인자는 다음의 역할을 합니다.

- document: 실행될 subscription을 가리킴.
- variables: subscription을 실행할 때 필요한 변수.
- updateQuery: Apollo Client에게 현재 쿼리의 캐시 데이터(prev)와 GraphQL 서버로부터 push된 subscriptionData를 어떻게 합쳐야 하는지 지정. return 값은 캐시되어 있는 쿼리의 결과를 대체함.

마지막으로, CommentsPage 컴포넌트에서 mount 할 때 subscribeToNewComments를 실행시켜줍니다.

```jsx
export class CommentsPage extends Component {
  componentDidMount() {
    this.props.subscribeToNewComments();
  }
}
```

> [https://www.apollographql.com/docs/react/data/subscriptions/](https://www.apollographql.com/docs/react/data/subscriptions/)

## subscribeToMore & unsubscribe

subscribeToMore 함수는 반환값으로 unsubscribe 함수를 반환합니다.

다음은 컴포넌트를 렌더링할 때 subscription을 구독하고, unmount 할 때 해지하는 코드입니다.

```jsx
...
  const { subscribeToNewMessage, chatLog, chatIndex, chatUUID } = props;
  useEffect(() => {
    const unsubscribe = subscribeToNewMessage({
      document: chatUUID,
    });
    return unsubscribe();
  });
...
```

[https://spectrum.chat/apollo/apollo-client/unsubscribe-subscribetomore~b7f64715-1a65-40d5-9147-5a6300de4e30](https://spectrum.chat/apollo/apollo-client/unsubscribe-subscribetomore~b7f64715-1a65-40d5-9147-5a6300de4e30)

# Managing local state

apollo client는 자체 캐시를 사용하여 localStorage 처럼 원하는 데이터를 로컬로 관리할 수 있습니다.

![image](https://user-images.githubusercontent.com/51621520/126443283-4cf56f22-1ae3-4da4-a64a-67055f090ec5.png)

출처: [https://www.apollographql.com/docs/react/local-state/local-state-management/](https://www.apollographql.com/docs/react/local-state/local-state-management/)

그리고 현재 입장한 채팅방의 uuid를 local state에 저장하였습니다.

## Field policies & Local-only fields

field policies는 특수한 필드에 쿼리를 정의할 수 있도록 해줍니다(GraphQL 서버 스키마에 정의되지 않은 필드).
local-only field에 대한 field policy들을 정의하여, localStorage나 reactive variable 같이 데이터를 어디서든 저장하고 가져올 수 있습니다.

단일 GraphQL 쿼리는 local-only fiel [...]

2021-07-22 04:34 UTC, jwon42 approved these changes
방대하네요. 적어놓으신 글 최대한 이해하면서 넘어가려고 질문도 하고 검색도 하다보니 시간이 꽤 걸렸습니다.
위에 있는 채팅을 읽다가 새로운 채팅이 감지되는 경우 스크롤을 땡겨주는 기능까지.. 고민도 많이 하신 것 같고 꼼꼼하게 작업하신 것 같아요. 수고하셨어요.

2021-07-22 04:36 UTC, yechoi42 approved these changes
와우👏👍

2021-07-22 04:36 UTC, yechoi42 commented on front/src/UI/organisms/AlarmChat/index.tsx
> +          }}
분리하면 보기 좋을 것 같아요 ~

2021-07-22 04:36 UTC, yechoi42 commented on back/src/chat-logs/chat-logs.resolver.ts
>      this.pubSubProvider.getPubSub().publish('chatLogAdded', { chatLogAdded: newChatLog });
subscription이 결국엔 mutation에 물리는 걸로 이해하면 될까요?

2021-07-22 05:32 UTC, yhshin0 commented on back/src/chat-logs/chat-logs.resolver.ts
>      this.pubSubProvider.getPubSub().publish('chatLogAdded', { chatLogAdded: newChatLog });
네 맞아요.

chatlog를 생성만 한다고 subscribe 할 수 있는 것이 아니라, 생성 이후 chatLogAdded 라는 subscription에 publish()를 해줘야 chatLogAdded를 subscribe 하고 있는 곳에서 캐치할 수 있습니다.

2021-07-22 09:47 UTC, hochan222 requested changes
정말 고생 많으셨습니다 ㅠㅠ 단위가 너무 커서 이해하는데 시간이 오래 걸려서 조금 늦었습니다. 다음에는 단위가 조금 더 작으면 리뷰하기 수월할 것 같습니다!

코드에서 다루지 못한 부분들에대해 추가적으로 몇가지 사항에 대해 커멘트 남겼습니다.

---

1. 
> reactive variables는 GraphQL을 사용하지 않아도 애플리케이션의 어디서든 local 데이터를 읽고 쓸 수 있도록 해줍니다.

혹시 어디에 브라우저에서 어느 공간에 저장되나요?

2. 
<img src="https://user-images.githubusercontent.com/22424891/126620118-287ae70f-f5a7-4fe9-ad84-31e8b5f4be7c.png" height="300px"/>

https://github.com/transcendence42/ft_transcendence/pull/99 해당 PR에서 말풍선 디자인이 병합되었는데요. 해당 PR에는 아래 사진과같이 반영이 되지않아서 확인 부탁드립니다. (로직상에서는 해당 로직이 처리돼있어서 확인 요청드렸습니다.)

<img src="https://user-images.githubusercontent.com/22424891/126620082-212a81fb-3a90-439d-9e4f-02e82c51b3e8.png" height="300px"/>

2021-07-22 09:47 UTC, hochan222 commented on front/src/UI/organisms/AlarmChat/index.tsx
> +      <AccordionItem>
밑에서 삼항연산자로 처리할수있을것같은데 하나의 render함수에서 처리가능함에도 여러군데에 긴 컴포넌트를 직접 작성해서 반환하는건 좋지 않습니다. 또한 다른 컴포넌트로 분리하는건 어떤가요?

2021-07-22 09:47 UTC, hochan222 commented on front/src/UI/organisms/AlarmChat/index.tsx
> +import React, { useRef, MouseEvent, useEffect } from 'react';
전체 로직을 하나의 파일로 작성했는데, 혹시 container presenter pattern 을 사용했을때하고 얻을 수 있는 이점은 어떤것이 있나요? 얻을 수 있는 이점이 작다면 container presenter pattern 으로 작성하는것이 나중에 누군가 해당 로직을 이해하는데 가독성 측면에서 좋다고 생각합니다.

2021-07-22 09:47 UTC, hochan222 commented on front/src/UI/organisms/AlarmChat/index.tsx
> +import { GET_CHAT, CHATLOG_SUBSCRIPTION } from './AlarmChatQueries';
import 부분에서 개행이 포함되고 기준없이 섞여있어서 리뷰했습니다.

2021-07-22 09:47 UTC, hochan222 commented on front/src/UI/organisms/AlarmChat/index.tsx
> +  const scrollRef = useRef();
```suggestion
  const scrollRef = useRef<타입을 지정해주자>(null);
```

ref의 초기값과 타입을 지정해야합니다.

2021-07-22 09:47 UTC, hochan222 commented on front/src/UI/organisms/AlarmChat/index.tsx
> +    if (scrollRef.current !== undefined && scrollRef.current !== null) {
```suggestion
    if (!scrollRef.current) {
```

아마 해당 부분도 위에 타입과 초기값을 지정하지않아 발생한것으로 보입니다. 그것과는 별도로 위와 같이 표현해도 문제없을것같은데 혹시 어떠한가요?

2021-07-22 09:47 UTC, hochan222 commented on front/src/UI/organisms/AlarmChat/index.tsx
> +      scrollRef.current.scrollBy(0, scrollRef.current.scrollHeight);
scrollBy 강제적으로 스크롤시키는 메소드군요! 새로운것 배워가요!

https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollBy
https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollBy
https://developer.mozilla.org/ko/docs/Web/API/Element/scrollHeight

2021-07-22 09:47 UTC, hochan222 commented on front/src/UI/organisms/AlarmChat/index.tsx
> +                  const res = Object.assign({}, prev, {
`Object.assign({},` 을 특별히 사용하신 이유가 있으신가요? (단순 호기심입니댜)

2021-07-22 09:47 UTC, hochan222 commented on front/src/UI/organisms/AlarmChat/index.tsx
> +                  if (!subscriptionData.data) return prev;
```suggestion
                  if (!subscriptionData.data) {return prev;}
```

{}는 꼭 한줄이여도 넣는게 가독성에서 좋다고 생각하빈다.

2021-07-22 09:47 UTC, hochan222 commented on front/src/UI/organisms/AlarmChatMessagesBox/index.tsx
> +import { AlarmChatMessage } from '../../molecules';
```suggestion

import { AlarmChatMessage } from '../../molecules';
```

외부 라이브러리와 개행으로 구분하는게 가독성 측면에서 좋습니다.

2021-07-22 09:47 UTC, hochan222 commented on front/src/UI/organisms/AlarmChatMessagesBox/index.tsx
> +  // 로그인 정보 가져오기
```suggestion

```

2021-07-22 09:47 UTC, hochan222 commented on front/src/UI/organisms/AlarmChatMessagesBox/index.tsx
> +    const unsubscribe = subscribeToNewMessage({
> subscribeToNewMessage={() =>

이해가 잘안돼서 리뷰했습니다. AlarmChatMessage에서 subscribeToNewMessage는 매개변수가 하나도 없는데 여기서는 인자가 있어서 이상합니다. 제가 어느 부분을 잘못 이해하고 있을까요?

2021-07-22 09:47 UTC, hochan222 commented on front/src/UI/organisms/AlarmChatMessagesBox/index.tsx
> +  const { data, loading, error } = useQuery(GET_CURRENT_USERID);
data.me.userID를 하나 얻어오기 위해서 쿼리를 요청했는데... 제 생각에는 좋지 않아보입니다.
좋지않다고 생각하는 이유는 아래와 같습니다. 

- data.me.userID 하나를 얻자고 쿼리를 날린다. (쿼리내용을 모두 요청한다. 아마 cash 문제로 모두 요청하는것으로 보인다.) 하나만 요청하더라도 충분히 다른 부분에서 가져올 수 있다고 생각합니다.
  - 1. apollo client의 Reactive variables로도 가져와서 처리할 수 있습니다.
  - 2. 로직상 AlarmChatMessage 에서 쿼리를 한번에 요청해서 넘겨주는게 더 적합하다고 생각합니다.

2021-07-22 09:47 UTC, hochan222 commented on front/src/UI/organisms/AlarmChatMessagesBox/index.tsx
> +    console.log(error);
```suggestion
```

2021-07-22 09:47 UTC, hochan222 commented on front/src/UI/organisms/AlarmChatMessagesBox/index.tsx
> +        type = type === 'notification' ? type : userID === data.me.userID ? 'ownerMessage' : 'message';
```suggestion
       const type = type === 'notification' ? type : userID === data.me.userID ? 'ownerMessage' : 'message';
```
뭔가 제가 잘못 설정한지모르겠습니다. const가 없는데도 lint err가 나지 않은건가요? 음.. 별도로 type은 따로 다른 이름으로 선언하는게 좋아보입니다.

2021-07-22 09:47 UTC, hochan222 commented on front/src/apollo/apolloProvider.ts
> +  uri: 'ws://127.0.0.1:5500/subscriptions',
> uri: GRAPHQL_URL,

위에 GRAPHQL_URL와 같이 contstant에서 관리가 필요해보입니다.

2021-07-22 09:47 UTC, hochan222 commented on front/src/apollo/apolloProvider.ts
> +import { WebSocketLink } from '@apollo/client/link/ws';
```suggestion
import { ApolloClient, InMemoryCache, HttpLink, split, makeVar, getMainDefinition, WebSocketLink } from '@apollo/client';
```

같은 패키지면 할 수 있을것같은데 이렇게는 임포트가 안되나요? (단순 호기심입니다!)

2021-07-22 09:47 UTC, hochan222 commented on front/src/apollo/apolloProvider.ts
> +              if (incoming !== undefined) {
```suggestion
              } else if (incoming !== undefined) {
```

따로 if로 분리하신 이유가 있으신지 궁금합니다.

2021-07-22 10:17 UTC, yhshin0 commented on back/tsconfig.json
> +    "skipLibCheck": true,
#121 에서 수정된 내용이네요
@yechoi42 설명 좀 부탁드릴게요

2021-07-22 10:22 UTC, jwon42 commented on back/tsconfig.json
> +    "skipLibCheck": true,
adminBro 적용 시 에러 체크를 위해 추가한걸로 압니다.
@yechoi42 설명이나 링크 부탁!

2021-07-22 10:27 UTC, yechoi42 commented on back/tsconfig.json
> +    "skipLibCheck": true,
https://github.com/transcendence42/ft_transcendence/issues/89#issuecomment-884051947 adminBro 설치하면서 type 중복으로 인한 에러 때문에 tsconfig.json에서 `"skipLibCheck": true,` 설정했습니다~  

A common case where you might think to use skipLibCheck is when there are two copies of a library’s types in your node_modules.

2021-07-22 10:38 UTC, hochan222 commented on back/tsconfig.json
> +    "skipLibCheck": true,
일부 adminBro가 타입스크립트로 작성되어있지 않아서 발생하는 오류군요. 이해했습니다!

2021-07-22 11:12 UTC, jwon42 approved these changes

2021-07-22 15:19 UTC, yhshin0 commented on front/src/apollo/apolloProvider.ts
> +              if (incoming !== undefined) {
existing, incoming이 둘 다 존재할 경우를 위해 else if 대신 if를 사용하였습니다.

2021-07-22 15:23 UTC, yhshin0 commented on front/src/UI/organisms/AlarmChat/index.tsx
> +      <AccordionItem>
해당 부분은 따로 컴포넌트로 분리하였습니다. 그러나 삼항연산자로 처리할 수는 없어보입니다.
왜냐하면 currentChat의 초기값은 빈 문자열이며, 렌더링 될 때 이를 인자로 하여 쿼리를 날릴 경우 에러를 반환합니다.
그래서 삼항연산자로 마지막에 사용할 수 없으며, 이를 위해 error 조건문에서 처리할 수 있도록 수정하였습니다.

2021-07-22 15:24 UTC, yhshin0 commented on front/src/UI/organisms/AlarmChat/index.tsx
> +                  const res = Object.assign({}, prev, {
일단 공식 문서에 있는 코드 스니펫을 참고하여 해당 코드를 작성하였습니다(https://www.apollographql.com/docs/react/data/subscriptions/#subscribing-to-updates-for-a-query).
그리고 assign을 사용한 이유는 prev가 null일 경우를 위해 사용한 것으로 추측됩니다.

2021-07-22 15:24 UTC, yhshin0 commented on front/src/UI/organisms/AlarmChatMessagesBox/index.tsx
> +    const unsubscribe = subscribeToNewMessage({
해당 부분은 https://spectrum.chat/apollo/apollo-client/unsubscribe-subscribetomore~b7f64715-1a65-40d5-9147-5a6300de4e30를 참고하였습니다.
그리고 AlarmChatMessage에서는 subscribeToNewMessage 함수를 사용하지 않습니다.
AlarmChat에서의 subscribeToNewMessage는 useQuery의 subscribeToMore 함수가 반환하는 함수로, subscription을 사용하는 곳에서 호출해야 합니다.

2021-07-22 15:24 UTC, yhshin0 commented on front/src/apollo/apolloProvider.ts
> +import { WebSocketLink } from '@apollo/client/link/ws';
해봤는데 안됩니다. `Module '"@apollo/client"' has no exported member 'WebSocketLink'.ts(2305)` 같은 에러 메시지가 발생합니다.

2021-07-22 16:10 UTC, yhshin0 commented
> 정말 고생 많으셨습니다 ㅠㅠ 단위가 너무 커서 이해하는데 시간이 오래 걸려서 조금 늦었습니다. 다음에는 단위가 조금 더 작으면 리뷰하기 수월할 것 같습니다!
> 
> 코드에서 다루지 못한 부분들에대해 추가적으로 몇가지 사항에 대해 커멘트 남겼습니다.
> 
> 
> > reactive variables는 GraphQL을 사용하지 않아도 애플리케이션의 어디서든 local 데이터를 읽고 쓸 수 있도록 해줍니다.
> 
> 혹시 어디에 브라우저에서 어느 공간에 저장되나요?

공식 홈페이지(https://www.apollographql.com/docs/react/local-state/local-state-management/)에는 reactive variable이 어디에 저장되는지 명시되어 있지 않습니다.
@apollo/client의 makeVar()를 통해 설정할 수 있으며, 전역변수처럼 메모리에 저장되어 관리될 것으로 추측됩니다.

> 
> <img alt="" height="300px" src="https://user-images.githubusercontent.com/22424891/126620118-287ae70f-f5a7-4fe9-ad84-31e8b5f4be7c.png">
> 
> #99 해당 PR에서 말풍선 디자인이 병합되었는데요. 해당 PR에는 아래 사진과같이 반영이 되지않아서 확인 부탁드립니다. (로직상에서는 해당 로직이 처리돼있어서 확인 요청드렸습니다.)

해당 부분은 스크롤을 설정하여 양쪽 끝이 보이지 않아 예상한 디자인으로 나오지 않은 것 같습니다.
AlarmChatMessage의 margin을 수정하여 끝이 보이도록 수정하였습니다.
<img src="https://user-images.githubusercontent.com/51621520/126670826-3b2d57ff-eed8-4b47-aa33-b2db69b70252.png" width="50%" />


> 
> <img alt="" height="300px" src="https://user-images.githubusercontent.com/22424891/126620082-212a81fb-3a90-439d-9e4f-02e82c51b3e8.png">
> 
> 추가적으로 기간에 대해서는 더미 데이터라서 -로 나오는건지 궁금합니다.

해당 데이터는 compareTimeLapseToString() 함수에서 첫번째 인자에 현재 시간, 두번째 인자에 createdAt을 넣어 발생한 이슈이며, 메시지 생성 시간과 분으로 표시하기 위해 코드를 수정하였습니다.
결과 화면은 아래와 같습니다.

<img src="https://user-images.githubusercontent.com/51621520/126671816-3f9247a7-94cf-404f-9056-80c0b9869dc1.png" width="50%" />

2021-07-23 01:48 UTC, hochan222 commented on front/src/UI/organisms/AlarmChat/index.tsx
> +                  const res = Object.assign({}, prev, {
오! 그렇군요!

> Object.assign() 메소드는 null 또는 undefined 출처 값에 대해서는 오류를 던지지 않음을 유의하세요.

https://developer.mozilla.org/ko/docs/orphaned/Web/JavaScript/Reference/Global_Objects/Object/assign

2021-07-23 01:54 UTC, hochan222 commented on front/src/UI/organisms/AlarmChatMessagesBox/index.tsx
> +    const unsubscribe = subscribeToNewMessage({
아.. return  이 생략돼있었군요... 여러줄인데 `{return }`이 없어서 혼동했습니다. 이해했습니다.

2021-07-23 02:11 UTC, hochan222 approved these changes
수정사항에 대한 리뷰 드립니다. 정말 고생 많이하셨습니다 ㅠㅠ

> @apollo/client의 makeVar()를 통해 설정할 수 있으며, 전역변수처럼 메모리에 저장되어 관리될 것으로 추측됩니다.

<img src="https://user-images.githubusercontent.com/22424891/126729496-ec8d8a22-4e67-4a80-a1a1-10cd895c3741.png" height="300px"/>

음.. 캐쉬나 로컬스토리지와는 다른 대안으로 적혀있는것보면 그런것 같네요..!

- https://www.apollographql.com/docs/react/local-state/managing-state-with-field-policies/

---

>해당 부분은 스크롤을 설정하여 양쪽 끝이 보이지 않아 예상한 디자인으로 나오지 않은 것 같습니다.
>AlarmChatMessage의 margin을 수정하여 끝이 보이도록 수정하였습니다.

좌우 스크롤은 따로 스크롤바가 안나와서 제가 인지를 못했군요! 고생하셨습니다 ㅠㅠ

---

> 해당 데이터는 compareTimeLapseToString() 함수에서 첫번째 인자에 현재 시간, 두번째 인자에 createdAt을 넣어 발생한 이슈이며, 예시지 생성 시간과 분으로 표시하기 위해 코드를 수정하였습니다.

👍 👍 👍

2021-07-23 02:11 UTC, hochan222 commented on front/src/UI/organisms/AlarmChat/index.tsx
> +    });
```suggestion
  const subscribeToNewMessage = () => {
    return subscribeToMore({
      document: CHATLOG_SUBSCRIPTION,
      variables: { uuid: currentChat },
      updateQuery: (prev, { subscriptionData }) => {
        if (!subscriptionData.data) {
          return prev;
        }
        const newFeedItem = subscriptionData.data.chatLogAdded;
        const res = Object.assign({}, prev, {
          chat: {
            chatLog: [...prev.chat.chatLog, newFeedItem],
          },
        });
        return res;
      },
    });
  }
```

2021-07-23 02:11 UTC, hochan222 commented on front/src/UI/organisms/AlarmChat/index.tsx
> +        <Flex flexDirection="column" height="258px" overflowX="hidden" overflowY="auto" ref={scrollRef}>
magic number

2021-07-23 06:23 UTC, merged